### ISSUE TITLE
Multi-arch build

### ISSUE THREAD

**Issue by copiltembel** [baresip/docker#16]
I've made a fork where I've modified the github actions to build multi-arch images of libre and baresip (only for stable atm):

https://github.com/baresip/docker/compare/main...copiltembel:baresip_docker:main

My issue is that when running on github's infra, the jobs get cancelled after ~30 minutes. I don't know why.

But I did build locally and pushed to my ghcr account:

```
$ docker buildx build libre --platform linux/amd64,linux/arm64 --build-arg VERSION=v3.8.0 -t ghcr.io/copiltembel/libre-dev:v3.8.0 --push
```

```
$ docker buildx build baresip --platform linux/arm64,linux/amd64 --build-arg VERSION=v3.8.0 --build-arg IMAGE=ghcr.io/copiltembel/libre-dev:v3.8.0 -t ghcr.io/copiltembel/baresip:v3.8.0 --push
```

And this seemed to have worked fine (I can see the tab **OS/Arch** with the expected entries): 

https://github.com/users/copiltembel/packages/container/package/libre-dev
https://github.com/users/copiltembel/packages/container/package/baresip

Do you have any idea why this fails on github actions?

**Comment by sreimers** [comment]
Multi-arch builds are now supported.
